### ISSUE TITLE
Hash code generation

### ISSUE THREAD

**Issue by nikhilDigiplusIT** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#1]
iam not able to generate the proper hash code
error: tr write error
is there any easy way to generate the hash code
thanks in advance

**Comment by hanatharesh2712** [comment]
@nikhilDigiplusIT You can add below plugin in your Cordova/Ionic APP and after getting the hash of your application you can remove an below-mentioned plugin from your APP. 

**To get the hash of your APP, Install this plugin:**
`ionic cordova plugin add https://github.com/hanatharesh2712/ionic-native-sms-retriever-plugin-master-hash.git`

After installing this plugin you have to call the plugin method as below code and it will show toast message(hash of your APP) in your device/emulator.
You need to call below retriveSMS() function to see your hash of APP.
```
var app = {
    retriveSMS: function() {
        window['cordova']['plugins']['smsRetriever']['startWatching'](
      // the first callback is the success callback. We got back the native code’s result here.
      (result) => { 
		console.log('Message', result);
	  },
      // the second is the error callback where we get back the errors
      (err) => {
        console.log(err);
      }
    );
    }
};
```

**Comment by hanatharesh2712** [comment]
@nikhilDigiplusIT Added a method(e.g. getAppHash) in the plugin to get APP hash code.
