### ISSUE TITLE
Class file for com.google.android.gms.internal.zzbej not found

### ISSUE THREAD

**Issue by eishynena** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#10]
When i tried to install sms retriever manager for cordova, and after build android, this error appear:

error: cannot access zzbej String from = message.getFrom(); ^ class file for com.google.android.gms.internal.zzbej not found Note: Some input files use or override a deprecated API.
    
   
This is de package.json

        {
          "name": "bancrecer-pagoya-movil",
          "version": "0.0.1",
          "author": "Ionic Framework",
          "homepage": "http://ionicframework.com/",
          "private": true,
          "scripts": {
            "clean": "ionic-app-scripts clean",
            "build": "ionic-app-scripts build",
            "lint": "ionic-app-scripts lint",
            "ionic:build": "ionic-app-scripts build",
            "ionic:serve": "ionic-app-scripts serve"
          },
          "dependencies": {
            "@angular/animations": "5.2.9",
            "@angular/common": "5.2.9",
            "@angular/compiler": "^6.1.10",
            "@angular/compiler-cli": "^6.1.10",
            "@angular/core": "5.2.9",
            "@angular/forms": "5.2.9",
            "@angular/http": "5.2.9",
            "@angular/platform-browser": "5.2.9",
            "@angular/platform-browser-dynamic": "5.2.9",
            "@ionic-native/android-fingerprint-auth": "^4.15.0",
            "@ionic-native/contacts": "^4.15.0",
            "@ionic-native/core": "4.6.0",
            "@ionic-native/deeplinks": "^4.15.0",
            "@ionic-native/device": "^4.15.0",
            "@ionic-native/keyboard": "^4.1.0",
            "@ionic-native/push": "^4.15.0",
            "@ionic-native/qr-scanner": "^4.12.2",
            "@ionic-native/social-sharing": "^4.15.0",
            "@ionic-native/splash-screen": "4.6.0",
            "@ionic-native/status-bar": "4.6.0",
            "@ionic/storage": "2.1.3",
            "@ng-idle/core": "^2.0.0-beta.12",
            "@ng-idle/keepalive": "^2.0.0-beta.12",
            "angular2-moment": "^1.7.0",
            "angular2-qrcode": "^2.0.1",
            "cordova-android": "^8.0.0",
            "cordova-ios": "^4.5.5",
            "cordova-plugin-android-fingerprint-auth": "^1.5.0",
            "cordova-plugin-contacts": "^3.0.1",
            "cordova-plugin-device": "^2.0.2",
            "cordova-plugin-ionic-keyboard": "^2.1.3",
            "cordova-plugin-ionic-webview": "^1.2.1",
            "cordova-plugin-qrscanner": "^2.6.2",
            "cordova-plugin-splashscreen": "^5.0.2",
            "cordova-plugin-whitelist": "^1.3.3",
            "cordova-plugin-x-socialsharing": "^5.4.4",
            "cordova-sqlite-storage": "^3.2.1",
            "cordova-support-google-services": "^1.1.0",
            "crypto-js": "^3.1.9-1",
            "crypto-md5": "^1.0.0",
            "es6-promise-plugin": "^4.2.2",
            "ionic-angular": "3.9.2",
            "ionic-plugin-deeplinks": "^1.0.19",
            "ionicons": "3.0.0",
            "phonegap-plugin-multidex": "^1.0.0",
            "phonegap-plugin-push": "^2.2.3",
            "rxjs": "5.5.8",
            "sw-toolbox": "3.6.0",
            "zone.js": "0.8.26"
          },
          "devDependencies": {
            "@ionic/app-scripts": "^3.2.0",
            "typescript": "~2.6.2"
          },
          "description": "An Ionic project",
          "cordova": {
            "plugins": {
              "cordova-plugin-whitelist": {},
              "cordova-plugin-device": {},
              "cordova-plugin-splashscreen": {},
              "cordova-plugin-ionic-keyboard": {},
              "cordova-plugin-qrscanner": {},
              "phonegap-plugin-push": {
                "SENDER_ID": "404114497437",
                "FCM_VERSION": "11.6.2",
                "ANDROID_SUPPORT_V13_VERSION": "27.+"
              },
              "cordova-plugin-android-fingerprint-auth": {},
              "cordova-sqlite-storage": {},
              "cordova-plugin-x-socialsharing": {
                "ANDROID_SUPPORT_V4_VERSION": "24.1.1+"
              },
              "cordova-plugin-contacts": {},
              "ionic-plugin-deeplinks": {
                "URL_SCHEME": "fspmovil",
                "DEEPLINK_SCHEME": "https",
                "DEEPLINK_HOST": "pago-movil.fin-soft.net",
                "ANDROID_PATH_PREFIX": "/",
                "ANDROID_2_PATH_PREFIX": "/",
                "ANDROID_3_PATH_PREFIX": "/",
                "ANDROID_4_PATH_PREFIX": "/",
                "ANDROID_5_PATH_PREFIX": "/",
                "DEEPLINK_2_SCHEME": " ",
                "DEEPLINK_2_HOST": " ",
                "DEEPLINK_3_SCHEME": " ",
                "DEEPLINK_3_HOST": " ",
                "DEEPLINK_4_SCHEME": " ",
                "DEEPLINK_4_HOST": " ",
                "DEEPLINK_5_SCHEME": " ",
                "DEEPLINK_5_HOST": " "
              },
              "cordova-plugin-ionic-webview": {},
              "cordova-support-google-services": {}
            },
            "platforms": [
              "ios",
              "android"
            ]
          }
        }
        
        This is the build.gradle from android folder
        
        
        apply plugin: 'com.android.application'
        
        buildscript {
            repositories {
                mavenCentral()
                google()
                jcenter()
            }
        
            dependencies {
                classpath 'com.android.tools.build:gradle:3.3.0'
            }
        }
        
        // Allow plugins to declare Maven dependencies via build-extras.gradle.
        allprojects {
            repositories {
                mavenCentral()
                jcenter()
            }
        }
        
        task wrapper(type: Wrapper) {
            gradleVersion = '4.10.3'
        }
        
        // Configuration properties. Set these via environment variables, build-extras.gradle, or gradle.properties.
        // Refer to: http://www.gradle.org/docs/current/userguide/tutorial_this_and_that.html
        ext {
            apply from: '../CordovaLib/cordova.gradle'
        
            // The value for android.compileSdkVersion.
            if (!project.hasProperty('cdvCompileSdkVersion')) {
                cdvCompileSdkVersion = null;
            }
            // The value for android.buildToolsVersion.
            if (!project.hasProperty('cdvBuildToolsVersion')) {
                cdvBuildToolsVersion = null;
            }
            // Sets the versionCode to the given value.
            if (!project.hasProperty('cdvVersionCode')) {
                cdvVersionCode = null
            }
            // Sets the minSdkVersion to the given value.
            if (!project.hasProperty('cdvMinSdkVersion')) {
                cdvMinSdkVersion = null
            }
            // Whether to build architecture-specific APKs.
            if (!project.hasProperty('cdvBuildMultipleApks')) {
                cdvBuildMultipleApks = null
            }
            // Whether to append a 0 "abi digit" to versionCode when only a single APK is build
            if (!project.hasProperty('cdvVersionCodeForceAbiDigit')) {
                cdvVersionCodeForceAbiDigit = null
            }
            // .properties files to use for release signing.
            if (!project.hasProperty('cdvReleaseSigningPropertiesFile')) {
                cdvReleaseSigningPropertiesFile = null
            }
            // .properties files to use for debug signing.
            if (!project.hasProperty('cdvDebugSigningPropertiesFile')) {
                cdvDebugSigningPropertiesFile = null
            }
            // Set by build.js script.
            if (!project.hasProperty('cdvBuildArch')) {
                cdvBuildArch = null
            }
        
            // Plugin gradle extensions can append to this to have code run at the end.
            cdvPluginPostBuildExtras = []
        }
        
        // PLUGIN GRADLE EXTENSIONS START
        apply from: "../cordova-plugin-qrscanner/demo-qrscanner.gradle"
        apply from: "../cordova-support-google-services/demo-build.gradle"
        apply from: "../phonegap-plugin-multidex/demo-multidex.gradle"
        // PLUGIN GRADLE EXTENSIONS END
        
        def hasBuildExtras1 = file('build-extras.gradle').exists()
        if (hasBuildExtras1) {
            apply from: 'build-extras.gradle'
        }
        
        def hasBuildExtras2 = file('../build-extras.gradle').exists()
        if (hasBuildExtras2) {
            apply from: '../build-extras.gradle'
        }
        
        // Set property defaults after extension .gradle files.
        if (ext.cdvCompileSdkVersion == null) {
            ext.cdvCompileSdkVersion = privateHelpers.getProjectTarget()
            //ext.cdvCompileSdkVersion = project.ext.defaultCompileSdkVersion
        }
        if (ext.cdvBuildToolsVersion == null) {
            ext.cdvBuildToolsVersion = privateHelpers.findLatestInstalledBuildTools()
            //ext.cdvBuildToolsVersion = project.ext.defaultBuildToolsVersion
        }
        if (ext.cdvDebugSigningPropertiesFile == null && file('../debug-signing.properties').exists()) {
            ext.cdvDebugSigningPropertiesFile = '../debug-signing.properties'
        }
        if (ext.cdvReleaseSigningPropertiesFile == null && file('../release-signing.properties').exists()) {
            ext.cdvReleaseSigningPropertiesFile = '../release-signing.properties'
        }
        
        // Cast to appropriate types.
        ext.cdvBuildMultipleApks = cdvBuildMultipleApks == null ? false : cdvBuildMultipleApks.toBoolean();
        ext.cdvVersionCodeForceAbiDigit = cdvVersionCodeForceAbiDigit == null ? false : cdvVersionCodeForceAbiDigit.toBoolean();
        ext.cdvMinSdkVersion = cdvMinSdkVersion == null ? defaultMinSdkVersion : Integer.parseInt('' + cdvMinSdkVersion)
        ext.cdvVersionCode = cdvVersionCode == null ? null : Integer.parseInt('' + cdvVersionCode)
        
        def computeBuildTargetName(debugBuild) {
            def ret = 'assemble'
            if (cdvBuildMultipleApks && cdvBuildArch) {
                def arch = cdvBuildArch == 'arm' ? 'armv7' : cdvBuildArch
                ret += '' + arch.toUpperCase().charAt(0) + arch.substring(1);
            }
            return ret + (debugBuild ? 'Debug' : 'Release')
        }
        
        // Make cdvBuild a task that depends on the debug/arch-sepecific task.
        task cdvBuildDebug
        cdvBuildDebug.dependsOn {
            return computeBuildTargetName(true)
        }
        
        task cdvBuildRelease
        cdvBuildRelease.dependsOn {
            return computeBuildTargetName(false)
        }
        
        task cdvPrintProps {
            doLast {
                println('cdvCompileSdkVersion=' + cdvCompileSdkVersion)
                println('cdvBuildToolsVersion=' + cdvBuildToolsVersion)
                println('cdvVersionCode=' + cdvVersionCode)
                println('cdvVersionCodeForceAbiDigit=' + cdvVersionCodeForceAbiDigit)
                println('cdvMinSdkVersion=' + cdvMinSdkVersion)
                println('cdvBuildMultipleApks=' + cdvBuildMultipleApks)
                println('cdvReleaseSigningPropertiesFile=' + cdvReleaseSigningPropertiesFile)
                println('cdvDebugSigningPropertiesFile=' + cdvDebugSigningPropertiesFile)
                println('cdvBuildArch=' + cdvBuildArch)
                println('computedVersionCode=' + android.defaultConfig.versionCode)
                android.productFlavors.each { flavor ->
                    println('computed' + flavor.name.capitalize() + 'VersionCode=' + flavor.versionCode)
                }
            }
        }
        
        android {
            defaultConfig {
                versionCode cdvVersionCode ?: new BigInteger("" + privateHelpers.extractIntFromManifest("versionCode"))
                applicationId privateHelpers.extractStringFromManifest("package")
        
                if (cdvMinSdkVersion != null) {
                    minSdkVersion cdvMinSdkVersion
                }
            }
        
            lintOptions {
              abortOnError false;
            }
        
            compileSdkVersion cdvCompileSdkVersion
            buildToolsVersion cdvBuildToolsVersion
        
            // This code exists for Crosswalk and other Native APIs.
            // By default, we multiply the existing version code in the
            // Android Manifest by 10 and add a number for each architecture.
            // If you are not using Crosswalk or SQLite, you can
            // ignore this chunk of code, and your version codes will be respected.
        
            if (Boolean.valueOf(cdvBuildMultipleApks)) {
                flavorDimensions "default"
        
                productFlavors {
                    armeabi {
                        versionCode defaultConfig.versionCode*10 + 1
                        ndk {
                            abiFilters = ["armeabi"]
                        }
                    }
                    armv7 {
                        versionCode defaultConfig.versionCode*10 + 2
                        ndk {
                            abiFilters = ["armeabi-v7a"]
                        }
                    }
                    arm64 {
                        versionCode defaultConfig.versionCode*10 + 3
                        ndk {
                            abiFilters = ["arm64-v8a"]
                        }
                    }
                    x86 {
                        versionCode defaultConfig.versionCode*10 + 4
                        ndk {
                            abiFilters = ["x86"]
                        }
                    }
                    x86_64 {
                        versionCode defaultConfig.versionCode*10 + 5
                        ndk {
                            abiFilters = ["x86_64"]
                        }
                    }
                }
            } else if (Boolean.valueOf(cdvVersionCodeForceAbiDigit)) {
                // This provides compatibility to the default logic for versionCode before cordova-android 5.2.0
                defaultConfig {
                    versionCode defaultConfig.versionCode*10
                }
            }
        
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_1_8
                targetCompatibility JavaVersion.VERSION_1_8
            }
        
            if (cdvReleaseSigningPropertiesFile) {
                signingConfigs {
                    release {
                        // These must be set or Gradle will complain (even if they are overridden).
                        keyAlias = ""
                        keyPassword = "__unset" // And these must be set to non-empty in order to have the signing step added to the task graph.
                        storeFile = null
                        storePassword = "__unset"
                    }
                }
                buildTypes {
                    release {
                        signingConfig signingConfigs.release
                    }
                }
                addSigningProps(cdvReleaseSigningPropertiesFile, signingConfigs.release)
            }
        
            if (cdvDebugSigningPropertiesFile) {
                addSigningProps(cdvDebugSigningPropertiesFile, signingConfigs.debug)
            }
        }
        
        /*
         * WARNING: Cordova Lib and platform scripts do management inside of this code here,
         * if you are adding the dependencies manually, do so outside the comments, otherwise
         * the Cordova tools will overwrite them
         */
        
        
        dependencies {
            implementation fileTree(dir: 'libs', include: '*.jar')
            // SUB-PROJECT DEPENDENCIES START
            implementation(project(path: ":CordovaLib"))
            implementation "com.android.support:support-v4:24.1.1+"
            implementation "com.android.support:support-v13:27.+"
            implementation "me.leolin:ShortcutBadger:1.1.17@aar"
            implementation "com.google.firebase:firebase-messaging:11.6.2"
            // SUB-PROJECT DEPENDENCIES END
        }
        
        def promptForReleaseKeyPassword() {
            if (!cdvReleaseSigningPropertiesFile) {
                return;
            }
            if ('__unset'.equals(android.signingConfigs.release.storePassword)) {
                android.signingConfigs.release.storePassword = privateHelpers.promptForPassword('Enter key store password: ')
            }
            if ('__unset'.equals(android.signingConfigs.release.keyPassword)) {
                android.signingConfigs.release.keyPassword = privateHelpers.promptForPassword('Enter key password: ');
            }
        }
        
        gradle.taskGraph.whenReady { taskGraph ->
            taskGraph.getAllTasks().each() { task ->
              if(['validateReleaseSigning', 'validateSigningRelease', 'validateSigningArmv7Release', 'validateSigningX76Release'].contains(task.name)) {
                 promptForReleaseKeyPassword()
              }
            }
        }
        
        def addSigningProps(propsFilePath, signingConfig) {
            def propsFile = file(propsFilePath)
            def props = new Properties()
            propsFile.withReader { reader ->
                props.load(reader)
            }
        
            def storeFile = new File(props.get('key.store') ?: privateHelpers.ensureValueExists(propsFilePath, props, 'storeFile'))
            if (!storeFile.isAbsolute()) {
                storeFile = RelativePath.parse(true, storeFile.toString()).getFile(propsFile.getParentFile())
            }
            if (!storeFile.exists()) {
                throw new FileNotFoundException('Keystore file does not exist: ' + storeFile.getAbsolutePath())
            }
            signingConfig.keyAlias = props.get('key.alias') ?: privateHelpers.ensureValueExists(propsFilePath, props, 'keyAlias')
            signingConfig.keyPassword = props.get('keyPassword', props.get('key.alias.password', signingConfig.keyPassword))
            signingConfig.storeFile = storeFile
            signingConfig.storePassword = props.get('storePassword', props.get('key.store.password', signingConfig.storePassword))
            def storeType = props.get('storeType', props.get('key.store.type', ''))
            if (!storeType) {
                def filename = storeFile.getName().toLowerCase();
                if (filename.endsWith('.p12') || filename.endsWith('.pfx')) {
                    storeType = 'pkcs12'
                } else {
                    storeType = signingConfig.storeType // "jks"
                }
            }
            signingConfig.storeType = storeType
        }
        
        for (def func : cdvPluginPostBuildExtras) {
            func()
        }
        
        // This can be defined within build-extras.gradle as:
        //     ext.postBuildExtras = { ... code here ... }
        if (hasProperty('postBuildExtras')) {
            postBuildExtras()
        }
        
        
  And this is de project.properties
        
        # This file was originally created by the Android Tools, but is now
        # used by cordova-android to manage the state of the various third party
        # libraries used in your application
        
        # This is the Library Module that contains the Cordova Library, this is not
        # required when using an AAR
        
        # This is the application project.  This is only required for Android Studio Gradle projects
        
        # Project target.
        target=android-28
        android.library.reference.1=CordovaLib
        android.library.reference.2=app
        cordova.gradle.include.1=cordova-plugin-qrscanner/demo-qrscanner.gradle
        cordova.system.library.1=com.android.support:support-v4:24.1.1+
        cordova.system.library.2=com.android.support:support-v13:27.+
        cordova.gradle.include.2=cordova-support-google-services/demo-build.gradle
        cordova.gradle.include.3=phonegap-plugin-multidex/demo-multidex.gradle
        cordova.system.library.3=me.leolin:ShortcutBadger:1.1.17@aar
        cordova.system.library.4=com.google.firebase:firebase-messaging:11.6.2

**Comment by hanatharesh2712** [comment]
Hi, I don't think this issue is related to SMS retriever manager plugin. 

you should try first following steps:
1) Delete plugins folder from your project
2) Remove platforms folder using `ionic cordova platform rm android/ios`
3) run command:` ionic cordova prepare android/ios`
4) and build for android or ios

Thanks

**Comment by eishynena** [comment]
I did it but not solved nothing :s .... I made a new project to see wich plugin is breaking my app. I create a new issue with another question https://github.com/hanatharesh2712/ionic-native-sms-retriever-plugin-master/issues/11

**Comment by hanatharesh2712** [comment]
Please make sure you have aligned all plugins Play_service version to same for all the plugins which use play services like push plugin, social sharing and sms retriver.etc.

**Comment by hanatharesh2712** [comment]
closing as no response for a while
