### ISSUE TITLE
Not working on IONIC 3 Not getting AppHashKey

### ISSUE THREAD

**Issue by tnssuet021** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#12]
Hi it's not working on ionic 3 can you please update it is giving below error : 

ERROR TypeError: Object(...) is not a function
    at SmsRetriever.getAppHash (index.js:28)
    at LoginProcessPage.webpackJsonp.51.LoginProcessPage.getAppHashKey

**Comment by hanatharesh2712** [comment]
@posdevelopers You can find Ionic 3 working example: [https://github.com/hanatharesh2712/sms-plugin-test-ionic-3](https://github.com/hanatharesh2712/sms-plugin-test-ionic-3)

**Comment by tnssuet021** [comment]
Not working giving below error var smsRetriever = window['cordova']['plugins']['smsRetriever'];
Runtime error
TypeError: Cannot read property 'plugins' of undefined

**Comment by tnssuet021** [comment]
![errer](https://user-images.githubusercontent.com/35066568/71595610-2c65a300-2b5e-11ea-9b5b-f640ff5312f0.png)

**Comment by tnssuet021** [comment]
SORRY ITS MY MISTAKE I AM NOT RUNNING ON MOBILE DEVICE, NOW ITS WORKING... THANK YOU.
YOU ARE TIME SAVER 
THANK YOU ONCE AGAIN

**Comment by tnssuet021** [comment]
ISSUE CLOSE AND RESOLVED SUCCESSFULLY GET APP HASH CODE ON IONIC 3
