### ISSUE TITLE
BUILD FAILED after installing cordova-plugin-sms-retriever-manager plugin

### ISSUE THREAD

**Issue by Ashoka222** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#13]
I have installed cordova-plugin-sms-retriever-manager plugin with
`ionic cordova plugin add cordova-plugin-sms-retriever-manager`
`npm install @ionic-native/sms-retriever`
command but the build is getting failed.

The error message is like 

> * What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 10.+.

I have updated the versions with 10.+, 11.+, 15.+ but this will not works. I have also updated some versions from the Android SDK Manager.

Please guide me to resolve this issue or suggest any other plugin to retrieve SMS for getting Auto-OTP.

Thanks in advance. :)

**Comment by hanatharesh2712** [comment]
@Ashoka222 refer this link: https://github.com/hanatharesh2712/ionic-native-sms-retriever-plugin-master/issues/5#issuecomment-499094995

**Comment by hanatharesh2712** [comment]
closing as no response for a while

**Comment by NabeelHaris** [comment]
First Install:-
1) ionic cordova resources
After that install:-
2) ionic cordova plugin add cordova-plugin-sms-retriever-manager
3) npm install @ionic-native/sms-retriever
than:-
4) ionic cordova build android/ios
