### ISSUE TITLE
Uncaught TypeError: Cannot read property 'smsRetriever' of undefined

### ISSUE THREAD

**Issue by tnssuet021** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#14]
It gives some time this error Uncaught TypeError: Cannot read property 'smsRetriever' of undefined

After Splash screen it shows this error on ionic 3 , i have followed your ionic 3 example i am running this on device

**Comment by hanatharesh2712** [comment]
@posdevelopers Make sure that you are calling plugin methods after device(platform) ready event.

Here is the working example
https://github.com/hanatharesh2712/ionic-native-sms-retriever-plugin-master/issues/11#issuecomment-568655748
