### ISSUE TITLE
SMS Retriever not works on release apk it's work fine on debug and production version

### ISSUE THREAD

**Issue by tnssuet021** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#16]
HI thank you for the wonderful services , I am here to write to you that currently i have signed my apk and when installing apk it's first said google play protect so i allow to install application , after it's install  window['cordova']['plugins']['smsRetriever']['startWatching'] it does not come to this method so it's not read the sms .same thing works fine on --prod version . i am using ionic 3 .
Please guide 

Thanks
Taimoor

**Comment by hanatharesh2712** [comment]
You can find Ionic 3 working example: [https://github.com/hanatharesh2712/sms-plugin-test-ionic-3](url)

**Comment by tnssuet021** [comment]
Ok i got it resolved for release version you have to generate new hash key after signing your app and then use new hash key in app to works in case if someone have the same problem

**Comment by MaYoRr** [comment]
> 

I have same problem, can you help me?
