### ISSUE TITLE
Google play rejected the app, Requested permissions do not match core functionality of the app

### ISSUE THREAD

**Issue by tnssuet021** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#17]
Hi there , i am trying to upload apk to google playstore but they have rejected my app due mentioned error 
"Requested permissions do not match core functionality of the app"

I am using smsretriever do i need to submit anything else to google or why it says that SMS functionality although i am not using sms read permissions 

Please guide 

Thank you
Taimoor

**Comment by hanatharesh2712** [comment]
@posdevelopers You may have some other plugins which are using some permissions. This plugin does not ask/need any permissions.

**Comment by tnssuet021** [comment]
Yes bro you are right i am using previously RECEIVE_SMS permission that's why it's asking .Thank you for prompt answer and wonderful support
