### ISSUE TITLE
sms not reading not working after uploading on google playstore.

### ISSUE THREAD

**Issue by codeclub2020** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#18]
Hi,
I have used sms-retriever-plugin to read sms for OTP verification and it works fine when we build debug apk and test.
After uploading on google play store it is not reading sms and not working.

Can anyone please help me,not getting where i am stuck.
Thanks in advance.

**Comment by hanatharesh2712** [comment]
@codeclub2020 Are you using release version hash code of your APP? If not then you have to use different hash string for release APK. Thanks!

**Comment by rahul-maurya1992** [comment]
Hi @codeclub2020 , 
Can you please let me know how can i generate release version hash code which accept by this plugin?

thank you.

**Comment by hanatharesh2712** [comment]
@rahul-maurya1992 You can refer updated readme.md file. 
![sms plugin demo](https://user-images.githubusercontent.com/17156331/95211391-2518a780-080a-11eb-9fd1-e1f75608956f.png)

**Comment by 9meAhmed** [comment]
i have signed my APK and its was working fine and then i uploaded to store after downloading from store its not working 
it there and change after apk uploaded to store

**Comment by hanatharesh2712** [comment]
@9meAhmed If it is signed with different certificates then you have to generate a hash string using that APK file.
