### ISSUE TITLE
app crashing after plugin installation

### ISSUE THREAD

**Issue by jyprksh001** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#2]
I implemented this plugin in my app but the app starts crashing when I install the plugin in my project(not even implemented the plugin in the project)

**Comment by hanatharesh2712** [comment]
@jyprksh001  You may be using some other plugins which use google play services. so, make sure that all plugins are using the same version of google play services.

You can see in you config.xml file, In which this plugin default use play services version 15.0.1
`<preference name="PLAY_SERVICES_VERSION" default="15.0.1"/>`

If you are using other plugins which use a different version of play services then you have to align all plugins play services version.

You can change this plugin play services version by changing above mentioned tag.

Please copy your config.xml and package.json file for more info.

Thanks!

**Comment by hanatharesh2712** [comment]
No response
