### ISSUE TITLE
Can i use this plugin in phoneGap. Please help

### ISSUE THREAD

**Issue by vaibhavWebgile** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#20]
Uncaught TypeError: Cannot read property 'startWatching' of undefined
    at retriveSMS (index.html:160)
    at Channel.onDeviceReady (index.html:155)
    at Channel.fire (cordova.js:868)
    at cordova.js:225

**Comment by hanatharesh2712** [comment]
@vaibhavWebgile Yes, you can use this plugin. You can find the working demo here for Cordova/PhoneGap: [https://github.com/hanatharesh2712/automatic-sms-cordova/tree/main/hello](https://github.com/hanatharesh2712/automatic-sms-cordova/tree/main/hello)

also, You can refer updated [readme.md](https://github.com/hanatharesh2712/ionic-native-sms-retriever-plugin-master#using-the-plugin) file.
