### ISSUE TITLE
[Question] how many hash do we need to create

### ISSUE THREAD

**Issue by indraraj26** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#22]
Q. do we need to create two hash one for play store and one for internal ?

Q. is hash depend upon the app id ? if i changed the app id do i need to create hash ?

**Comment by hanatharesh2712** [comment]
@indraraj26 

Q. do we need to create two hash one for play store and one for internal ?
     _- Yes, We need to create one hash for signed APK file(to upload on playstore) and one for internal(not signed)._

Q. is hash depend upon the app id ? if i changed the app id do i need to create hash ?
    _- hash depends on our application package id(`<widget id="io.ionic.starter"`) which we mention in the config.xml file. and If we change the app id then we need to create new hash for that as well._
