### ISSUE TITLE
Unable to enable user consent using the plugin

### ISSUE THREAD

**Issue by munene2019** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#23]
How I enable user consent or read sms senderid using this plugin. Currently, it seems to read all messages with the set hashcode despite the varying senderid. This makes the app vulnerable.

**Comment by hanatharesh2712** [comment]
@munene2019 You mean, You need to have sender info with message content?

**Comment by munene2019** [comment]
Yeah,i need the send id to avoid forwarding of OTP so as to be used to do
the validation of the sender

**Comment by hanatharesh2712** [comment]
@munene2019 It won't help much.. but, will look into this in future. If you would like to help in this then I am happy to accept the PR. :)
