### ISSUE TITLE
How to read SMS without hash?

### ISSUE THREAD

**Issue by bkrajendra** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#28]
is there anyways to read sms without hash?
I want to read SMS/OTP from the different systems where I don't want to use any hashing.
I just need to read numbers or entire SMS from it.

**Comment by hanatharesh2712** [comment]
@bkrajendra In general, there is no way to read SMS without the hash. For Some app like Truecaller,  It read all the SMS. 
and this kind of permissions you need to request to Google and they might give you the permissions to read all the SMS.

**Comment by bkrajendra** [comment]
Thanks for the clarification. 
I wonder how some payment applications read OTP coming from different payment gateway without the hash.
Do you think they also read all SMS?

Anyways. thanks for the reply.
