### ISSUE TITLE
 Failed to transform play-services-auth-api-phone-15.0.1.jar

### ISSUE THREAD

**Issue by alitalaee** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#32]
When Run ionic cordova build android --prod gives me an error 

<img width="844" alt="Screen Shot 1400-07-16 at 07 19 13" src="https://user-images.githubusercontent.com/77755450/136495281-688609b4-e531-4544-8494-bd3062b82840.png">

ionic info 
`
Ionic:

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 10.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 20 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.4.1)   : 1.3.0

System:

   ios-deploy : 1.11.0
   NodeJS     : v12.18.3 (/usr/local/bin/node)
   npm        : 6.14.6
   OS         : macOS Big Sur
   Xcode      : Xcode 12.5.1 Build version 12E507`

I Use FCM To Notification Is there any conflict? 

` "cordova-plugin-fcm-with-dependecy-updated": {
      "FCM_VERSION": "19.0.0",
      "GRADLE_TOOLS_VERSION": "3.5.3",
      "GOOGLE_SERVICES_VERSION": "4.3.3",
      "SUPPORT_LIBRARY_VERSION": "28.0.0",
      "ANDROID_DEFAULT_NOTIFICATION_ICON": "@mipmap/ic_launcher",
      "PACKAGE_NAME": "app.neshankala.com"
    },`

SMS RETRIVER IN package.json
`"cordova-plugin-sms-retriever-manager": {
        "PLAY_SERVICES_VERSION": "15.0.0"
      },
`

**Comment by alitalaee** [comment]
It seems this issue happen in ionic android platform 10.x.x+ and it is work on ionic android platform less than 10. my project use android platform 10.1.0 to support android 11. please help me to fix  this issue

**Comment by hanatharesh2712** [comment]
@alitalaee you are using different play services version. So, you have to align the play services version in all the plugins which use play services.

**Comment by alitalaee** [comment]
> @alitalaee you are using different play services version. So, you have to align the play services version in all the plugins which use play services.

can you explain more please i dont understand what do you mean

**Comment by alitalaee** [comment]
> > @alitalaee you are using different play services version. So, you have to align the play services version in all the plugins which use play services.
> 
> can you explain more please i dont understand what do you mean

please give me something to help more

**Comment by hanatharesh2712** [comment]
@alitalaee You are using Play services version `19.0.0` for `cordova-plugin-fcm-with-dependecy-updated` pluing and `15.0.0` for `cordova-plugin-sms-retriever-manager` plugin. so, you need to use same play services version for both the plugins. 
You can use 19.0.0 for both plugin. by changing the `{ "PLAY_SERVICES_VERSION": "15.0.0" } `in package.json file
