### ISSUE TITLE
I am not able to run the command ionic cordova plugin add cordova-plugin-sms-retriever-manager

### ISSUE THREAD

**Issue by kunalSBasic** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#36]
Whenever I try to run the command **ionic cordova plugin add cordova-plugin-sms-retriever-manager** it always throw this error.

> cordova.cmd plugin add cordova-plugin-sms-retriever-manager
Failed to fetch plugin cordova-plugin-sms-retriever-manager via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: Error: npm: Command failed with exit code 1 Error output:
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.  
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @angular-devkit/build-angular@14.2.1
npm ERR! Found: @angular/compiler-cli@11.2.0
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   dev @angular/compiler-cli@"~11.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler-cli@"^14.0.0" from @angular-devkit/build-angular@14.2.1        
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"^14.2.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/compiler-cli@14.2.0
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^14.0.0" from @angular-devkit/build-angular@14.2.1      
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"^14.2.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\Legion\AppData\Local\npm-cache\eresolve-report.txt for a full report.    

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Legion\AppData\Local\npm-cache\_logs\2022-08-30T08_11_44_886Z-debug-0.log
[ERROR] An error occurred while running subprocess cordova.
        
        cordova.cmd plugin add cordova-plugin-sms-retriever-manager exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.

**Comment by hanatharesh2712** [comment]
@kunalSBasic it seems issue with your npm registry config. You can try to install with below command

 ionic cordova plugin add cordova-plugin-sms-retriever-manager@1.0.3
