### ISSUE TITLE
After the release in the market, the plugin does not work

### ISSUE THREAD

**Issue by MaYoRr** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#38]
When I make a build version of the apk, autofill works, when I make an aab file for the market, it does not work. The certificates are the same
` "@ionic-native/core": "^5.36.0",
    "@ionic-native/sms-retriever": "^5.36.0",`

**Comment by hanatharesh2712** [comment]
This should help you: https://github.com/hanatharesh2712/ionic-native-sms-retriever-plugin-master/issues/22
