### ISSUE TITLE
NullPointerException Println needs a message : Throwing Exception while reading messages

### ISSUE THREAD

**Issue by mejainankit** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#39]
It is throwing exception, while reading the message. 
If message doesn't have the hash. This plugin reads the message and sends a null message with status as success, which further throws an exception **NullPointerException: Println needs a message** at the following line.

 **_Log.d(TAG, message);_**

```
 case CommonStatusCodes.SUCCESS:
              final String message = extra.getString(SmsRetriever.EXTRA_SMS_MESSAGE);
              //if (!StringUtils.hasContent(message)) return;

             Log.d(TAG, message);

              data = new JSONObject();
              try {
                data.put("Message",message);
              } catch(JSONException e) {}

              //Toast.makeText(cordova.getActivity().getApplicationContext(),"Message: "+ message, Toast.LENGTH_LONG).show();
              PluginResult result = new PluginResult(PluginResult.Status.OK, data);
              callbackContext.sendPluginResult(result);

              break;

```

**Comment by mejainankit** [comment]
@hanatharesh2712 Here is the PR for the same [https://github.com/hanatharesh2712/ionic-native-sms-retriever-plugin-master/pull/40](https://github.com/hanatharesh2712/ionic-native-sms-retriever-plugin-master/pull/40)

**Comment by hanatharesh2712** [comment]
@mejainankit Latest npm package(1.0.4) is available now. Thanks!
