### ISSUE TITLE
SMS is not reading

### ISSUE THREAD

**Issue by Ram12393** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#6]
I successfully installed this plugin in my ionic application, I tried to use the read SMS, but unfortunately, it is not reading any SMS. could you help me with this regard

**Comment by hanatharesh2712** [comment]
Are you sending SMS with your hash code with below format?

<#> Your ExampleApp code is: 123ABC78 YOUR_HASH_CODE_HERE

e.g: <#> Your ExampleApp code is: 123ABC78 FA+9qCX9VSu

**Comment by PunitSaharan** [comment]
i am using this following code its not working in ionic 4..i got App Hash that code working fine but reading sms code not working.

```
ngOnInit() {

    this.start();
  }

start() {
  
  this.smsRetriever.startWatching()
  .then((res: any) => alert(res))
  .catch((error: any) => alert(error));
  
  }
```

i tried to set alert but not alert come either on response or error.

My sms Template is also same as u mentioned : <#> Your ExampleApp code is: 123ABC78 FA+9qCX9VSu

**Comment by hanatharesh2712** [comment]
Wait fot 5 minutes after start watching function. You will get timeout error. And make sure that you are sending sms with your app hash string

**Comment by hanatharesh2712** [comment]
closing as no response for a while
