### ISSUE TITLE
Cannot read property 'plugins' of undefined

### ISSUE THREAD

**Issue by abhishek3999** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#7]
I was trying to integrate this plugin with ionic 3 application.Got this error.
Please help!

**Comment by hanatharesh2712** [comment]
You can find Ionic 3 working example: https://github.com/hanatharesh2712/sms-plugin-test-ionic-3

**Comment by hanatharesh2712** [comment]
closing as no response for a while
