### ISSUE TITLE
What about iOS?

### ISSUE THREAD

**Issue by TechRova** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#8]
Does your plugin support iOS SMS reading also?

What will happen when I am running the app in iOS with your plugin running?

**Comment by hanatharesh2712** [comment]
No, iOS does not provide the SMS read functionality like as we have in Android. 
You need to run the plugin only when the platform is Android. you can check the platform using like: https://ionicframework.com/docs/utilities/platform

**Comment by TechRova** [comment]
> No, iOS does not provide the SMS read functionality like as we have in Android.
> You need to run the plugin only when the platform is Android. you can check the platform using like: https://ionicframework.com/docs/utilities/platform

Yeah OK

Please suggest a plugin to read iOS SMS OTP ?

**Comment by hanatharesh2712** [comment]
Unfortunately, there is no plugin to read SMS in iOS. Thanks!

**Comment by kunalSBasic** [comment]
Is there any update on any plugin like this for iOS?
